name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          patchAll: true
          token: ${{ github.token }}
          branch: main

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}